# Generated by Django 4.1.7 on 2023-03-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='unit',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
