# Generated by Django 4.1.7 on 2023-03-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_alter_unit_code_alter_unit_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitEnrollment',
        ),
    ]
