# Generated by Django 4.1.7 on 2023-03-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='major_course_of_study',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='name',
        ),
    ]
