# Generated by Django 4.1.7 on 2023-03-14 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0003_delete_unitenrollment'),
        ('Class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('unit_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('student_reg_no', models.IntegerField()),
                ('cat1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cat2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cat3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_exam', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.DeleteModel(
            name='UnitEnrollment',
        ),
    ]
