# Generated by Django 4.1.7 on 2023-03-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0002_class_classenrollment_delete_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classenrollment',
            name='student_reg_no',
            field=models.CharField(max_length=100),
        ),
    ]
