# Generated by Django 4.1.7 on 2023-03-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0003_alter_classenrollment_student_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classenrollment',
            name='cat1',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='classenrollment',
            name='cat2',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='classenrollment',
            name='cat3',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='classenrollment',
            name='final_exam',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
